# Generated by Django 4.2.6 on 2025-08-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
